namespace: bootstrap
name: workshop

version: 0.1.0
readme: README.md

authors:
  - Christopher Engleby <cengleby@redhat.com>

description: A Collection used to bootstrap poc-workshops

license:
  - MIT

tags: []

dependencies: {}

repository: https://github.com/poc-examples/ansible-collections
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker
